### ISSUE TITLE
Hi, Idk why this repo is in my "repo list" but not in my profile?...

### ISSUE THREAD

**Issue by TheKillerTacos** [ILOVEMCPE/PocketMine-MP#3]
So, came back from a trip, and found this in my repo list, but not in my profile, Im not even in ILOVEMCPE, but looks like THERE ARE A TON of cool plugins, but why is this for?
i dont think for development reasons.. but i guess someone can point me in if help needed

**Comment by UltimateMcraft** [comment]
It says 'ready made server' ...

**Comment by flaxues** [comment]
You are just subscribed to this channel!
