### ISSUE TITLE
Software Votes!! Join now for vote

### ISSUE THREAD

**Issue by MateiGamingYTB** [ILOVEMCPE/PocketMine-MP#5]
Vote foor server software!?

ImagicalMine
BukkitPE
Genisys
PocketMine-MP
ClearSky

Vote now for server sofwware now....
P.S.
On this Server PHP7 Coming Soom Adding

**Comment by AndreTheGamer** [comment]
:+1:  For [BukkitPE](https://www.github.com/BukkitPE/BukkitPE)  :)

**Comment by MateiGamingYTB** [comment]
your BukkitPE software is accepted add you PocketMine-PM.phar in this responsibility

**Comment by MateiGamingYTB** [comment]
BukkitPE is parteners vs this server?

**Comment by AndreTheGamer** [comment]
ok.....

**Comment by TheKillerTacos** [comment]
CLEARSKY, fastest MCPE server with PM Core, can use about no ram and really low load,

**Comment by MateiGamingYTB** [comment]
I tested ImagicalMine, Genisys, BukkitPE on PHP7 my private server (no`t this) and server running very good I (dislike) ClearSky sorry Vote more people for ClearSky for adding to the server.....

**Comment by MateiGamingYTB** [comment]
add more plugins on responsibility and more Features and testing please for verify of function server

**Comment by MateiGamingYTB** [comment]
testing will all software`s

**Comment by Driesboy** [comment]
genisys

**Comment by flaxues** [comment]
Genisys!

**Comment by MateiGamingYTB** [comment]
ok I testing Genisys now

**Comment by TheClimbing** [comment]
Genisys!

**Comment by MateiGamingYTB** [comment]
ok I adding genisys now time

**Comment by TheClimbing** [comment]
Superrr

**Comment by TheKillerTacos** [comment]
GENISYS, ClearSky is crap now...

**Comment by MateiGamingYTB** [comment]
TheClimbing  you are Romanian?
esti roman???

**Comment by TheClimbing** [comment]
@MateiGamingYTB Close I'm bulgarian.What about you?

**Comment by MateiGamingYTB** [comment]
you speak Magyar?

**Comment by MateiGamingYTB** [comment]
for wath closed?

**Comment by Driesboy** [comment]
genisys work best.

**Comment by MateiGamingYTB** [comment]
add genisys now.....I not have genisys I have imagicalmine on my hosted server

**Comment by GabiYT** [comment]
Cenisys pentru ca da. Acum lucreaza la "Cenisys" in C++

**Comment by MateiGamingYTB** [comment]
Vrei Sa te adaug la contributor? Sal bag tu Si Sa ne ajuti?

**Comment by GabiYT** [comment]
Ok

**Comment by MateiGamingYTB** [comment]
accepta cererea sa intri la contributori si baga genisys si pluginuri daca vrei

**Comment by GabiYT** [comment]
Dami skypeul tau. App uite ilovemcpe.github.io

**Comment by GabiYT** [comment]
Skype-ul meu e gabitza200431. Hai sa vb acolo

**Comment by MateiGamingYTB** [comment]
gaby.matei2 e skypeul facebookul e Endre Endi
